version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=post_pwd
      - POSTGRES_DB=ticket_bot_db
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data

#  nginx:
#    depends_on:
#      - server
#    environment:
#      - REACT_APP_SERVER_NAME='http://localhost:5000/api'
#      - REACT_APP_SERVER_NAME_PUBLIC='http://localhost:5000'
#    restart: always
#    build: ./react-app
#    ports:
#      - "80:80"

  server:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_USER=postgres
      - DB_HOST=postgres
      - DB_NAME=ticket_bot_db
      - DB_PASSWORD=post_pwd
      - DB_PORT=5432
      - FOREST_ENV_SECRET=366f9f2d5d6db1578985ab515bee7d68bde34628067dff4f17e57c1b5e704842
      - FOREST_AUTH_SECRET=c2f14196864b16a6a3d09cc3d85c45b8bf9f5ae6f732b604
      - FOREST_AGENT_URL=https://ticket-bot.online
      - SECRET_KEY=ama_secret_key
    restart: always

volumes:
  postgres_db: